from fpdf import FPDF
import datetime


class CyberReport(FPDF):

    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_fill_color(31, 56, 100)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, 'Cybersecurity Report', fill=True, ln=True, align='C')
        self.set_text_color(0, 0, 0)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Confidential | Generated by cyber-report-generator', align='C')

    def cover_page(self, title, target, analyst, report_type):
        self.add_page()
        self.ln(20)
        self.set_font('Helvetica', 'B', 28)
        self.set_text_color(31, 56, 100)
        self.cell(0, 15, title, ln=True, align='C')
        self.ln(5)
        self.set_font('Helvetica', '', 14)
        self.set_text_color(80, 80, 80)
        self.cell(0, 10, f'Report Type: {report_type}', ln=True, align='C')
        self.cell(0, 10, f'Target: {target}', ln=True, align='C')
        self.cell(0, 10, f'Analyst: {analyst}', ln=True, align='C')
        self.cell(0, 10, f'Date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', ln=True, align='C')
        self.ln(20)
        self.set_font('Helvetica', 'I', 11)
        self.set_text_color(150, 0, 0)
        self.cell(0, 10, 'CONFIDENTIAL - For Authorized Personnel Only', ln=True, align='C')

    def section_title(self, title):
        self.ln(5)
        self.set_font('Helvetica', 'B', 13)
        self.set_fill_color(31, 56, 100)
        self.set_text_color(255, 255, 255)
        self.cell(0, 9, f'  {title}', fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def severity_badge(self, severity):
        colors = {
            'Critical': (200, 0, 0),
            'High': (220, 80, 0),
            'Medium': (200, 150, 0),
            'Low': (0, 150, 0),
            'Info': (0, 100, 200)
        }
        r, g, b = colors.get(severity, (128, 128, 128))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 9)
        self.cell(20, 6, severity, fill=True, align='C')
        self.set_text_color(0, 0, 0)

    def executive_summary(self, summary_data):
        self.section_title('Executive Summary')
        self.set_font('Helvetica', '', 11)
        total = summary_data.get('total_findings', 0)
        critical = summary_data.get('critical', 0)
        high = summary_data.get('high', 0)
        medium = summary_data.get('medium', 0)
        low = summary_data.get('low', 0)
        self.multi_cell(0, 7, (
            f'This report presents the findings from a security assessment. '
            f'A total of {total} security findings were identified. '
            f'Of these, {critical} Critical, {high} High, {medium} Medium, and {low} Low severity. '
            f'All findings include detailed descriptions and remediation guidance.'
        ))
        self.ln(3)
        cols = [('Total', total), ('Critical', critical), ('High', high), ('Medium', medium), ('Low', low)]
        col_width = 35
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(220, 220, 220)
        for label, _ in cols:
            self.cell(col_width, 8, label, border=1, fill=True, align='C')
        self.ln()
        self.set_font('Helvetica', '', 10)
        for _, value in cols:
            self.cell(col_width, 8, str(value), border=1, align='C')
        self.ln(5)

    def add_nmap_findings(self, data):
        self.section_title('Network Scan Findings (nmap)')
        self.set_font('Helvetica', '', 10)
        host = data.get('host', 'Unknown')
        self.multi_cell(0, 6, f'Network scanning performed against {host}. Open ports and services identified below.')
        self.ln(3)
        findings = data.get('findings', [])
        if not findings:
            self.set_font('Helvetica', 'I', 10)
            self.cell(0, 8, 'No open ports found.', ln=True)
            return
        for i, f in enumerate(findings, 1):
            self.set_font('Helvetica', 'B', 11)
            self.set_fill_color(240, 240, 240)
            self.cell(0, 8, f'Finding {i}: {f.get("port", "")} - {f.get("service", "").upper()}', fill=True, ln=True)
            self.ln(2)
            self.set_font('Helvetica', 'B', 10)
            self.cell(35, 6, 'Port / State:', ln=False)
            self.set_font('Helvetica', '', 10)
            self.cell(0, 6, f'{f.get("port", "")} ({f.get("state", "")})', ln=True)
            self.set_font('Helvetica', 'B', 10)
            self.cell(35, 6, 'Severity:', ln=False)
            self.severity_badge(f.get('severity', 'Info'))
            self.ln(8)
            self.set_font('Helvetica', 'B', 10)
            self.cell(0, 6, 'Description:', ln=True)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, f.get('description', ''))
            self.ln(5)

    def add_nikto_findings(self, data):
        self.section_title('Web Vulnerability Findings (nikto)')
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, 'Web application scanning performed using nikto. Findings include risk description and remediation steps.')
        self.ln(3)
        findings = data.get('findings', [])
        if not findings:
            self.set_font('Helvetica', 'I', 10)
            self.cell(0, 8, 'No web vulnerabilities found.', ln=True)
            return
        for i, f in enumerate(findings, 1):
            self.set_font('Helvetica', 'B', 11)
            self.set_fill_color(240, 240, 240)
            self.cell(0, 8, f'Finding {i}: {f.get("title", "Web Finding")}', fill=True, ln=True)
            self.ln(2)
            self.set_font('Helvetica', 'B', 10)
            self.cell(35, 6, 'Severity:', ln=False)
            self.severity_badge(f.get('severity', 'Low'))
            self.ln(8)
            self.set_font('Helvetica', 'B', 10)
            self.cell(0, 6, 'Description:', ln=True)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, f.get('description', ''))
            self.ln(2)
            self.set_font('Helvetica', 'B', 10)
            self.cell(0, 6, 'Remediation:', ln=True)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, f.get('remediation', ''))
            self.ln(5)

    def add_dirb_findings(self, data):
        self.section_title('Directory Enumeration Findings (dirb)')
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, 'Directory enumeration performed using dirb. Accessible paths discovered below.')
        self.ln(3)
        findings = data.get('findings', [])
        if not findings:
            self.set_font('Helvetica', 'I', 10)
            self.cell(0, 8, 'No directories or files found.', ln=True)
            return
        for i, f in enumerate(findings, 1):
            self.set_font('Helvetica', 'B', 11)
            self.set_fill_color(240, 240, 240)
            self.cell(0, 8, f'Finding {i}: {f.get("type", "Resource")} Discovered', fill=True, ln=True)
            self.ln(2)
            self.set_font('Helvetica', 'B', 10)
            self.cell(35, 6, 'Path:', ln=False)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, f.get('path', ''))
            self.set_font('Helvetica', 'B', 10)
            self.cell(35, 6, 'Severity:', ln=False)
            self.severity_badge(f.get('severity', 'Low'))
            self.ln(8)
            self.set_font('Helvetica', 'B', 10)
            self.cell(0, 6, 'Remediation:', ln=True)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, f.get('remediation', ''))
            self.ln(5)

    def add_soc_incident(self, data):
        self.section_title('Incident Details')
        self.set_font('Helvetica', 'B', 11)
        self.set_x(self.l_margin)
        self.cell(40, 8, 'Incident Title:', ln=False)
        self.set_font('Helvetica', '', 11)
        self.cell(0, 8, data.get('title', ''), ln=True)
        self.set_font('Helvetica', 'B', 11)
        self.set_x(self.l_margin)
        self.cell(40, 8, 'Severity: ', ln=False)
        sev = data.get('severity', 'Medium')
        self.set_font('Helvetica', '', 11)
        self.cell(0, 8, sev, ln=True)
        self.ln(5)

        if data.get('affected_systems'):
            self.section_title('Affected Systems')
            self.set_font('Helvetica', '', 10)
            for system in data.get('affected_systems', []):
                self.set_x(self.l_margin)
                self.multi_cell(0, 6, f'- {system}')

        if data.get('timeline'):
            self.section_title('Incident Timeline')
            self.set_font('Helvetica', '', 10)
            for event in data.get('timeline', []):
                self.set_x(self.l_margin)
                t = f'{event.get("time", "")}  {event.get("event", "")}'
                self.multi_cell(0, 6, t)
                self.ln(1)

        if data.get('indicators'):
            self.section_title('Indicators of Compromise (IOCs)')
            self.set_font('Helvetica', '', 10)
            for ioc in data.get('indicators', []):
                self.set_x(self.l_margin)
                self.multi_cell(0, 6, f'- {ioc}')

        if data.get('response_actions'):
            self.section_title('Response Actions Taken')
            self.set_font('Helvetica', '', 10)
            for action in data.get('response_actions', []):
                self.set_x(self.l_margin)
                self.multi_cell(0, 6, f'- {action}')

    def add_recommendations(self, report_type):
        self.section_title('Recommendations')
        self.set_font('Helvetica', '', 10)
        recs = {
            'pentest': [
                ('Critical/High', 'Immediately patch or mitigate all Critical and High severity findings within 7 days.'),
                ('Network Exposure', 'Review all exposed services. Restrict MySQL (3306) to localhost only. Close unnecessary ports.'),
                ('Web Security', 'Implement all missing security headers across all web applications.'),
                ('Session Security', 'Enforce HttpOnly and Secure flags on all session cookies.'),
                ('Information Disclosure', 'Remove phpinfo.php and restrict access to configuration directories.'),
                ('Patch Management', 'Keep all software updated within 30 days of security patches being released.'),
                ('WAF', 'Implement a Web Application Firewall for additional protection against common web attacks.'),
            ],
            'soc': [
                ('Immediate', 'Conduct a full forensic investigation of all affected systems before restoration.'),
                ('Credentials', 'Reset all credentials for potentially compromised accounts including service accounts.'),
                ('Containment', 'Verify complete isolation of affected systems and confirm no lateral movement.'),
                ('Evidence', 'Preserve all logs, memory dumps, and disk images for forensic analysis.'),
                ('Communication', 'Notify stakeholders including management, legal, and affected parties per your IR plan.'),
                ('Recovery', 'Restore systems from verified clean backups only after forensic analysis is complete.'),
                ('Lessons Learned', 'Conduct a post-incident review within 72 hours and update IR playbooks.'),
            ],
            'vulnerability': [
                ('Prioritization', 'Address Critical within 24 hours, High within 7 days, Medium within 30 days.'),
                ('Patch Management', 'Implement a formal vulnerability management program with defined SLAs.'),
                ('Regular Assessment', 'Schedule quarterly vulnerability assessments and annual penetration tests.'),
                ('Risk Register', 'Maintain a risk register to track findings, remediation status, and risk acceptance.'),
                ('Verification', 'Conduct remediation verification scans after fixes are applied.'),
            ]
        }
        for priority, rec in recs.get(report_type, recs['pentest']):
            self.set_font('Helvetica', 'B', 10)
            self.cell(0, 6, f'{priority}:', ln=True)
            self.set_font('Helvetica', '', 10)
            self.multi_cell(0, 6, rec)
            self.ln(3)
