name: CI - Cyber Report Generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 main.py src/parsers.py src/report_generator.py --max-line-length=120 --ignore=E501,W503

      - name: Create reports directory
        run: mkdir -p reports

      - name: Test pentest report generation
        run: python main.py pentest --target "172.18.0.3" --analyst "Test Analyst" --nmap samples/nmap_output.txt --nikto samples/nikto_output.txt --output reports/test_report.pdf

      - name: Test SOC report generation
        run: python main.py soc --incident-file samples/incident.json --analyst "Test Analyst" --output reports/test_soc.pdf

      - name: Verify reports were generated
        run: |
          test -f reports/test_report.pdf && echo "Pentest report generated OK"
          test -f reports/test_soc.pdf && echo "SOC report generated OK"
